### ISSUE TITLE
Generic helper functions for maps & arrays in CCI config

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/circle-policy-agent#35]
We are seeing some common basic functions that make assertions in config easier.

- `in_array` - for objects like `context`  which can be a list or single value makes checking match either case.
- `job_name` - since jobs of a `worklows` can be a single string, or include things like  custom `name` this uses the right name in either case.

....  Others?

**Comment by davidmdm** [comment]
@eddiewebb 

For the first part point we have created `circleci.utils` that has a `to_set` and `to_array` helpers.

So suppose you wanted to check if a context was in a worflow's job's context field:

```rego
import future.keywords
import data.circleci.utils

prod_is_used = "prod" in utils.to_set(input.workflows.main.jobs[_].context)
```

For the second point, this would be useful helper!!!! What name would we give it since this pattern of "string literal" | "object of with 1 key to configuration" is used for jobs in workflows, for steps in jobs, and probably elsewhere...

If we made it:

```rego
import data.circleci.config

config.get_element_name(input.jobs.example.steps[0])
```

would that be satisfatory? get_element_name | get_item_name? Any perference?
